{% set name = "PedPy" %}
{% set version = "1.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PedPy-{{ version }}.tar.gz
  sha256: b3a8edd8afee21219e6a723bbcc0946e03aa765396d96b6cc66ca96d9776520d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - versioneer
    - pip
  run:
    - python >=3.8
    - aenum ==3.1.11
    - numpy ==1.23.0
    - pandas ==1.5.1
    - shapely ==2.0.1
    - scipy ==1.9.3
    - matplotlib-base ==3.6.1

test:
  imports:
    - pedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PedestrianDynamics/pedpy
  summary: PedPy is a Python module for pedestrian movement analysis.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PedestrianDynamics/pedpy
  doc_url: https://pedpy.readthedocs.io/

extra:
  recipe-maintainers:
    - schroedtert
